### ISSUE TITLE
API TOKENをファイルで読み込めるようにしたいね

### ISSUE THREAD

**Issue by pitsuHU** [wakuwinmail/karayama2020#1]

**Comment by Nhara777** [comment]
こういうのとか使えますかね
https://miyabikno-jobs.com/slackbot-api-token/#slackbot-token-osenv

**Comment by Nhara777** [comment]
https://miyabikno-jobs.com/slackbot-api-token/#slackbot-token-osenv

**Comment by wakuwinmail** [comment]
apitoken.txtにAPIトークンを書いて同じディレクトリに置くと読み込めるようになった。
